using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AutoMap;

[Generator]
public sealed class AutoMapGenerator : IIncrementalGenerator
{
    // ── Attributes emitted into the user's compilation ────────────────────────

    private const string AttributeSource = @"// <auto-generated by AutoMap.Generator/>
#nullable enable
using System;

namespace AutoMap
{
    /// <summary>Generates a To{DestName}() extension method mapping this type to <paramref name=""destinationType""/>.</summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class MapAttribute : Attribute
    {
        public Type DestinationType { get; }
        /// <summary>Override the generated method name. Default: ""To{DestinationTypeName}"".</summary>
        public string? MethodName { get; set; }
        /// <summary>Also generate the reverse mapping (destination → source).</summary>
        public bool Reverse { get; set; }
        public MapAttribute(Type destinationType) { DestinationType = destinationType; }
    }

    /// <summary>Generates a To{ThisName}() extension method on <paramref name=""sourceType""/> that maps to this type.</summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class MapFromAttribute : Attribute
    {
        public Type SourceType { get; }
        /// <summary>Override the generated method name. Default: ""To{ThisTypeName}"".</summary>
        public string? MethodName { get; set; }
        /// <summary>Also generate the reverse mapping (this type → source type).</summary>
        public bool Reverse { get; set; }
        public MapFromAttribute(Type sourceType) { SourceType = sourceType; }
    }

    /// <summary>Excludes this destination property from all generated mappings.</summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapIgnoreAttribute : Attribute { }

    /// <summary>Maps this destination property from a differently-named source property.</summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapPropertyAttribute : Attribute
    {
        public string SourceName { get; }
        public MapPropertyAttribute(string sourceName) { SourceName = sourceName; }
    }

    /// <summary>
    /// Maps this destination property using a custom C# expression.
    /// Use <c>src</c> to reference the source object.
    /// Example: <c>[MapWith(""src.Price.ToString(\""C2\"")"")]</c>
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapWithAttribute : Attribute
    {
        /// <summary>A C# expression using <c>src</c> as the source variable.</summary>
        public string Expression { get; }
        public MapWithAttribute(string expression) { Expression = expression; }
    }

    /// <summary>
    /// Substitutes this C# expression when the source value is null.
    /// The expression is emitted as the right-hand side of <c>?? expr</c>.
    /// Example: <c>[MapDefault(""\""N/A\"""")]</c> emits <c>src.Name ?? ""N/A""</c>.
    /// Works with flattened paths: <c>src.Customer?.Name ?? ""Unknown""</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapDefaultAttribute : Attribute
    {
        /// <summary>A C# expression to use when the source property is null.</summary>
        public string DefaultExpression { get; }
        public MapDefaultAttribute(string defaultExpression) { DefaultExpression = defaultExpression; }
    }

    /// <summary>
    /// Instructs AutoMap.Generator to use a specific constructor when creating the destination type.
    /// When omitted, AutoMap.Generator automatically uses constructor mapping whenever the destination
    /// type has no public parameterless constructor (e.g. positional records, primary-constructor classes).
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class MapConstructorAttribute : Attribute { }

    /// <summary>
    /// Placed on a source enum member to redirect it to a differently-named destination enum value.
    /// Example: <c>[MapEnum(""Running"")]</c> on <c>SourceStatus.Active</c> maps to <c>DestStatus.Running</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false)]
    public sealed class MapEnumAttribute : Attribute
    {
        public string DestValueName { get; }
        public MapEnumAttribute(string destValueName) { DestValueName = destValueName; }
    }

    /// <summary>
    /// Maps this destination property only when the given C# condition expression evaluates to <c>true</c>.
    /// Use <c>src</c> to reference the source object.
    /// When the condition is false, <see cref=""Fallback""/> is used (default: <c>default</c>).
    /// Example: <c>[MapWhen(""src.IsActive"")]</c> emits <c>src.IsActive ? src.Prop : default</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapWhenAttribute : Attribute
    {
        /// <summary>A C# boolean expression using <c>src</c>. When true, the property is mapped normally.</summary>
        public string Condition { get; }
        /// <summary>C# expression emitted when <see cref=""Condition""/> is false. Defaults to <c>default</c>.</summary>
        public string? Fallback { get; set; }
        public MapWhenAttribute(string condition) { Condition = condition; }
    }
}
";

    private const string InterfaceSource = @"// <auto-generated by AutoMap.Generator/>
#nullable enable

namespace AutoMap
{
    /// <summary>Strongly-typed mapper generated by AutoMap.Generator. Use <see cref=""AutoMapExtensions""/> for the static instance.</summary>
    public interface IAutoMapper<in TSource, out TResult>
    {
        /// <summary>Maps <paramref name=""source""/> to <typeparamref name=""TResult""/>.</summary>
        TResult Map(TSource source);
    }
}
";

    // ── Diagnostics ──────────────────────────────────────────────────────────

    private static readonly DiagnosticDescriptor AM001 = new DiagnosticDescriptor(
        "AM001",
        "No properties mapped",
        "Mapping from '{0}' to '{1}' produced no property matches. Ensure property names and types align, or add [MapIgnore] to suppress.",
        "AutoMap",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap#am001");

    private static readonly DiagnosticDescriptor AM002 = new DiagnosticDescriptor(
        "AM002",
        "MapProperty source name not found",
        "[MapProperty(\"{0}\")] on '{1}.{2}' references a property that does not exist on source type '{3}'",
        "AutoMap",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap#am002");

    private static readonly DiagnosticDescriptor AM004 = new DiagnosticDescriptor(
        "AM004",
        "Property skipped due to type incompatibility",
        "Property '{0}' on '{1}' was skipped: source property '{2}' on '{3}' has an incompatible type with no registered mapping. Use [MapIgnore] to suppress, or add [Map] on the source type",
        "AutoMap",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap.Generator#am004");

    private static readonly DiagnosticDescriptor AM003 = new DiagnosticDescriptor(
        "AM003",
        "Mapping target type could not be resolved",
        "The type passed to [{0}] on '{1}' could not be resolved. Ensure the type is accessible.",
        "AutoMap",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap.Generator#am003");

    private static readonly DiagnosticDescriptor AM005 = new DiagnosticDescriptor(
        "AM005",
        "Constructor parameter has no matching source property",
        "Constructor parameter '{0}' on destination type '{1}' has no matching property on source type '{2}'. The parameter will receive 'default' — add a source property with the same name or use [MapIgnore] to suppress.",
        "AutoMap",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap.Generator#am005");

    private static readonly DiagnosticDescriptor AM006 = new DiagnosticDescriptor(
        "AM006",
        "Enum value has no matching destination enum member",
        "Source enum member '{0}' on '{1}' has no matching member in destination enum '{2}'. Add [MapEnum(\"DestValueName\")] to specify the mapping, or ensure a same-named member exists. The _ fallback will emit default.",
        "AutoMap",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap.Generator#am006");

    // ── Initialize ────────────────────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoMapAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            ctx.AddSource("AutoMapInterface.g.cs",  SourceText.From(InterfaceSource,  Encoding.UTF8));
        });

        // [Map] — attribute sits on the source type
        var mapPipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoMap.MapAttribute",
                predicate: static (n, _) => IsTypeSyntax(n),
                transform: static (ctx, ct) => TransformAttributes(ctx, ct, isMapFrom: false))
            .SelectMany(static (arr, _) => arr);

        // [MapFrom] — attribute sits on the destination type
        var mapFromPipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoMap.MapFromAttribute",
                predicate: static (n, _) => IsTypeSyntax(n),
                transform: static (ctx, ct) => TransformAttributes(ctx, ct, isMapFrom: true))
            .SelectMany(static (arr, _) => arr);

        var allMappings = mapPipeline.Collect().Combine(mapFromPipeline.Collect());

        context.RegisterSourceOutput(allMappings, static (spc, pair) =>
            GenerateSource(spc, pair.Left.AddRange(pair.Right)));
    }

    private static bool IsTypeSyntax(SyntaxNode n) =>
        n is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax;

    // ── Transform: one call per decorated type, returns one MappingInfo per attribute ─

    private static ImmutableArray<MappingInfo> TransformAttributes(
        GeneratorAttributeSyntaxContext ctx,
        System.Threading.CancellationToken ct,
        bool isMapFrom)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol decoratedSymbol)
            return ImmutableArray<MappingInfo>.Empty;

        var builder = ImmutableArray.CreateBuilder<MappingInfo>(ctx.Attributes.Length);

        foreach (var attr in ctx.Attributes)
        {
            ct.ThrowIfCancellationRequested();

            if (attr.ConstructorArguments.Length == 0) continue;
            if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol otherSymbol)
            {
                // AM003 — type could not be resolved
                builder.Add(new MappingInfo(
                    string.Empty, string.Empty, string.Empty,
                    ImmutableArray<PropertyMapping>.Empty,
                    ImmutableArray<UnresolvedProperty>.Empty,
                    ImmutableArray.Create(new DiagnosticInfo("AM003",
                        ImmutableArray.Create(isMapFrom ? "MapFromAttribute" : "MapAttribute", decoratedSymbol.Name))),
                    false));
                continue;
            }

            var sourceSymbol = isMapFrom ? otherSymbol : decoratedSymbol;
            var destSymbol   = isMapFrom ? decoratedSymbol : otherSymbol;

            string? methodName = null;
            bool reverse = false;
            foreach (var na in attr.NamedArguments)
            {
                if (na.Key == "MethodName") methodName = na.Value.Value as string;
                if (na.Key == "Reverse"   ) reverse    = na.Value.Value is true;
            }

            builder.Add(BuildMappingInfo(sourceSymbol, destSymbol, methodName, ctx.SemanticModel.Compilation));

            // When Reverse = true, also generate the opposite direction
            if (reverse)
                builder.Add(BuildMappingInfo(destSymbol, sourceSymbol, null, ctx.SemanticModel.Compilation));
        }

        return builder.ToImmutable();
    }

    // ── Build one MappingInfo from resolved symbols ───────────────────────────

    private static MappingInfo BuildMappingInfo(
        INamedTypeSymbol sourceSymbol,
        INamedTypeSymbol destSymbol,
        string? methodName,
        Compilation compilation)
    {
        var sourceFqn = sourceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var destFqn   = destSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var effectiveMethod = methodName ?? "To" + destSymbol.Name;

        // Build a lookup of all readable source properties (name → symbol)
        var sourceProps = new Dictionary<string, IPropertySymbol>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in GetAllProperties(sourceSymbol))
        {
            if (p.IsStatic || p.IsIndexer) continue;
            if (p.GetMethod == null || p.GetMethod.DeclaredAccessibility != Accessibility.Public) continue;
            if (!sourceProps.ContainsKey(p.Name))
                sourceProps[p.Name] = p;
        }

        var mappings             = ImmutableArray.CreateBuilder<PropertyMapping>();
        var unresolvedProperties = ImmutableArray.CreateBuilder<UnresolvedProperty>();
        var diagnostics          = ImmutableArray.CreateBuilder<DiagnosticInfo>();

        foreach (var destProp in GetAllProperties(destSymbol))
        {
            if (destProp.IsStatic || destProp.IsIndexer) continue;

            // Must have a publicly accessible setter (regular or init)
            var setter = destProp.SetMethod;
            if (setter == null || setter.DeclaredAccessibility != Accessibility.Public) continue;

            // [MapIgnore]
            if (HasAttribute(destProp, "AutoMap.MapIgnoreAttribute")) continue;

            // Collect all per-property control attributes in one pass
            string? mapWithExpr    = null;
            string? mapDefaultExpr = null;
            string? mapWhenCond    = null;
            string? mapWhenFallback = null;
            string? srcOverrideName = null;

            foreach (var a in destProp.GetAttributes())
            {
                var fqn = a.AttributeClass?.ToDisplayString();
                if (fqn == "AutoMap.MapWithAttribute" && a.ConstructorArguments.Length > 0)
                    mapWithExpr = a.ConstructorArguments[0].Value as string;
                else if (fqn == "AutoMap.MapDefaultAttribute" && a.ConstructorArguments.Length > 0)
                    mapDefaultExpr = a.ConstructorArguments[0].Value as string;
                else if (fqn == "AutoMap.MapPropertyAttribute" && a.ConstructorArguments.Length > 0)
                    srcOverrideName = a.ConstructorArguments[0].Value as string;
                else if (fqn == "AutoMap.MapWhenAttribute" && a.ConstructorArguments.Length > 0)
                {
                    mapWhenCond = a.ConstructorArguments[0].Value as string;
                    foreach (var na in a.NamedArguments)
                        if (na.Key == "Fallback") mapWhenFallback = na.Value.Value as string;
                }
            }

            if (mapWithExpr != null)
            {
                // [MapWith] — custom expression, optionally wrapped by [MapWhen]
                var expr = mapWhenCond != null
                    ? $"{mapWhenCond} ? {mapWithExpr} : {mapWhenFallback ?? "default"}"
                    : mapWithExpr;
                mappings.Add(new PropertyMapping(destProp.Name, destProp.Name, expr));
                continue;
            }

            string lookupName = srcOverrideName ?? destProp.Name;

            if (!sourceProps.TryGetValue(lookupName, out var srcProp))
            {
                if (srcOverrideName != null)
                {
                    // AM002 — explicit source name missing
                    diagnostics.Add(new DiagnosticInfo("AM002",
                        ImmutableArray.Create(srcOverrideName, destSymbol.Name, destProp.Name, sourceSymbol.Name)));
                }
                else
                {
                    // Try flattening: CustomerName → src.Customer?.Name
                    var flatPath = TryFlattenPath(destProp.Name, sourceProps, "src", false, 0);
                    if (flatPath != null)
                    {
                        var expr = mapDefaultExpr != null ? $"{flatPath} ?? {mapDefaultExpr}" : flatPath;
                        mappings.Add(new PropertyMapping(destProp.Name, destProp.Name,
                            WrapWhen(expr, mapWhenCond, mapWhenFallback)));
                    }
                }
                continue;
            }

            // Check type compatibility
            var csharp = compilation as Microsoft.CodeAnalysis.CSharp.CSharpCompilation;
            bool typeCompatible;
            if (csharp != null)
            {
                var conv = csharp.ClassifyConversion(srcProp.Type, destProp.Type);
                typeCompatible = conv.IsIdentity || conv.IsImplicit;
            }
            else
            {
                var srcTypeFqn  = srcProp.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).TrimEnd('?');
                var destTypeFqn = destProp.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).TrimEnd('?');
                typeCompatible = srcTypeFqn == destTypeFqn;
            }

            if (typeCompatible)
            {
                string? finalExpr = null;
                if (mapDefaultExpr != null || mapWhenCond != null)
                {
                    var baseExpr = mapDefaultExpr != null
                        ? $"src.{lookupName} ?? {mapDefaultExpr}"
                        : $"src.{lookupName}";
                    finalExpr = WrapWhen(baseExpr, mapWhenCond, mapWhenFallback);
                }
                mappings.Add(new PropertyMapping(destProp.Name, lookupName, finalExpr));
            }
            else if (srcProp.Type.TypeKind == TypeKind.Enum
                  && destProp.Type.TypeKind == TypeKind.Enum
                  && srcProp.Type is INamedTypeSymbol srcEnum
                  && destProp.Type is INamedTypeSymbol destEnum)
            {
                var switchExpr = BuildEnumSwitchExpression(
                    $"src.{lookupName}", srcEnum, destEnum,
                    destEnum.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    diagnostics);
                mappings.Add(new PropertyMapping(destProp.Name, lookupName,
                    WrapWhen(switchExpr, mapWhenCond, mapWhenFallback)));
            }
            else
            {
                // May be resolvable as nested or collection mapping — defer to GenerateSource
                var unresolved = BuildUnresolvedProperty(destProp.Name, lookupName, srcProp.Type, destProp.Type);
                if (unresolved != null)
                    unresolvedProperties.Add(unresolved);
                // else: truly incompatible (e.g. different primitive types) — silently skip
            }
        }

        // ── Constructor mapping detection ──────────────────────────────────────
        // Use constructor mapping when:
        //   a) dest has [MapConstructor] attribute, OR
        //   b) dest has no public parameterless constructor
        bool hasParamlessCtor = false;
        foreach (var ctor in destSymbol.Constructors)
        {
            if (!ctor.IsStatic && ctor.DeclaredAccessibility == Accessibility.Public
                && ctor.Parameters.Length == 0)
            { hasParamlessCtor = true; break; }
        }

        bool hasMapConstructorAttr = HasAttribute(destSymbol, "AutoMap.MapConstructorAttribute");
        var ctorParams = ImmutableArray<CtorParamMapping>.Empty;

        if (!hasParamlessCtor || hasMapConstructorAttr)
        {
            // Pick the best (longest) public constructor
            IMethodSymbol? bestCtor = null;
            foreach (var ctor in destSymbol.Constructors)
            {
                if (ctor.IsStatic || ctor.DeclaredAccessibility != Accessibility.Public) continue;
                if (bestCtor == null || ctor.Parameters.Length > bestCtor.Parameters.Length)
                    bestCtor = ctor;
            }

            if (bestCtor != null)
            {
                var ctorBuilder = ImmutableArray.CreateBuilder<CtorParamMapping>(bestCtor.Parameters.Length);
                var ctorParamNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                foreach (var param in bestCtor.Parameters)
                {
                    sourceProps.TryGetValue(param.Name, out var matchedProp);

                    if (matchedProp == null)
                    {
                        // AM005 — no matching source property for ctor param
                        diagnostics.Add(new DiagnosticInfo("AM005",
                            ImmutableArray.Create(param.Name, destSymbol.Name, sourceSymbol.Name)));
                        ctorBuilder.Add(new CtorParamMapping(param.Name, null));
                    }
                    else
                    {
                        ctorBuilder.Add(new CtorParamMapping(param.Name, matchedProp.Name));
                        ctorParamNames.Add(matchedProp.Name);
                    }
                }

                ctorParams = ctorBuilder.ToImmutable();

                // Remove ctor-covered properties from object-initializer mappings to avoid duplication
                var filtered = ImmutableArray.CreateBuilder<PropertyMapping>();
                foreach (var pm in mappings)
                    if (!ctorParamNames.Contains(pm.SourcePropertyName))
                        filtered.Add(pm);
                mappings = filtered;
            }
        }

        // AM001 moved to GenerateSource (needs all mappings to know if deferred props resolve)
        return new MappingInfo(
            sourceFqn, destFqn, effectiveMethod,
            mappings.ToImmutable(),
            unresolvedProperties.ToImmutable(),
            diagnostics.ToImmutable(),
            sourceSymbol.IsValueType,
            ctorParams);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static IEnumerable<IPropertySymbol> GetAllProperties(INamedTypeSymbol type)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var current = (INamedTypeSymbol?)type;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is IPropertySymbol prop && seen.Add(prop.Name))
                    yield return prop;
            }
            current = current.BaseType;
        }
    }

    private static bool HasAttribute(ISymbol symbol, string fullyQualifiedName)
    {
        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.ToDisplayString() == fullyQualifiedName)
                return true;
        return false;
    }

    private static UnresolvedProperty? BuildUnresolvedProperty(
        string destPropName, string srcPropName, ITypeSymbol srcType, ITypeSymbol destType)
    {
        var srcFqn  = srcType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var destFqn = destType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var srcElemFqn  = GetCollectionElementFqn(srcType);
        var destElemFqn = GetCollectionElementFqn(destType);

        if (srcElemFqn != null && destElemFqn != null)
        {
            // Both are collection types
            string kind = destType is IArrayTypeSymbol ? "Array" : "List";
            return new UnresolvedProperty(destPropName, srcPropName, srcFqn, destFqn,
                isCollection: true, srcElemFqn, destElemFqn, kind);
        }

        if (srcElemFqn == null && destElemFqn == null)
        {
            // Both non-collection — potential nested object mapping
            return new UnresolvedProperty(destPropName, srcPropName, srcFqn, destFqn,
                isCollection: false, null, null, null);
        }

        return null; // mixed collection/non-collection — incompatible
    }

    private static string? GetCollectionElementFqn(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol arr)
            return arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (type is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Length == 1)
        {
            var def = named.OriginalDefinition.ToDisplayString();
            if (def is "System.Collections.Generic.List<T>"
                    or "System.Collections.Generic.IEnumerable<T>"
                    or "System.Collections.Generic.ICollection<T>"
                    or "System.Collections.Generic.IList<T>"
                    or "System.Collections.Generic.IReadOnlyList<T>"
                    or "System.Collections.Generic.IReadOnlyCollection<T>")
                return named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return null;
    }

    // ── Code generation ───────────────────────────────────────────────────────

    private static void GenerateSource(
        SourceProductionContext spc,
        ImmutableArray<MappingInfo> mappings)
    {
        // Build sourceFqn → (destFqn → methodName) lookup for resolving nested/collection
        var knownMappings = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
        foreach (var m in mappings)
        {
            if (string.IsNullOrEmpty(m.SourceFqn)) continue;
            if (!knownMappings.TryGetValue(m.SourceFqn, out var destMap))
                knownMappings[m.SourceFqn] = destMap = new Dictionary<string, string>(StringComparer.Ordinal);
            destMap[m.DestFqn] = m.MethodName;
        }

        // Resolve deferred (nested / collection) properties
        bool needsLinq = false;
        var resolvedExtras = new Dictionary<MappingInfo, List<(string DestProp, string Expr)>>();

        foreach (var m in mappings)
        {
            if (string.IsNullOrEmpty(m.SourceFqn)) continue;
            var extras = new List<(string, string)>();

            foreach (var up in m.UnresolvedProperties)
            {
                string? expr = null;

                if (up.IsCollection && up.SourceElementFqn != null && up.DestElementFqn != null)
                {
                    if (knownMappings.TryGetValue(up.SourceElementFqn, out var dm) &&
                        dm.TryGetValue(up.DestElementFqn, out var method))
                    {
                        needsLinq = true;
                        expr = up.DestCollectionKind == "Array"
                            ? $"src.{up.SourcePropertyName}?.Select(x => x.{method}()).ToArray()"
                            : $"src.{up.SourcePropertyName}?.Select(x => x.{method}()).ToList()";
                    }
                }
                else if (!up.IsCollection)
                {
                    if (knownMappings.TryGetValue(up.SourceTypeFqn, out var dm) &&
                        dm.TryGetValue(up.DestTypeFqn, out var method))
                    {
                        expr = $"src.{up.SourcePropertyName}?.{method}()";
                    }
                }

                if (expr != null)
                    extras.Add((up.DestPropertyName, expr));
                else
                    spc.ReportDiagnostic(Diagnostic.Create(AM004, null,
                        up.DestPropertyName, SimpleName(m.DestFqn),
                        up.SourcePropertyName, SimpleName(m.SourceFqn)));
            }

            resolvedExtras[m] = extras;
        }

        // Report stored diagnostics (AM002, AM003, AM005)
        foreach (var m in mappings)
        {
            foreach (var d in m.Diagnostics)
            {
                var descriptor = d.Id switch { "AM002" => AM002, "AM003" => AM003, "AM005" => AM005, "AM006" => AM006, _ => AM001 };
                spc.ReportDiagnostic(Diagnostic.Create(descriptor, null, d.Args.ToArray<object>()));
            }
        }

        // AM001 — no properties at all (direct or resolved)
        foreach (var m in mappings)
        {
            if (string.IsNullOrEmpty(m.SourceFqn) || m.Diagnostics.Length > 0) continue;
            var extras = resolvedExtras.TryGetValue(m, out var ex) ? ex : null;
            if (m.Mappings.Length == 0 && m.CtorParams.Length == 0 && (extras == null || extras.Count == 0))
                spc.ReportDiagnostic(Diagnostic.Create(AM001, null,
                    SimpleName(m.SourceFqn), SimpleName(m.DestFqn)));
        }

        // Emit only mappings that have at least one property
        var valid = mappings
            .Where(m => !string.IsNullOrEmpty(m.SourceFqn))
            .Where(m => m.Mappings.Length > 0 || m.CtorParams.Length > 0 ||
                        (resolvedExtras.TryGetValue(m, out var ex) && ex.Count > 0))
            .ToList();

        if (valid.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoMap.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        if (needsLinq)
        {
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
        }
        sb.AppendLine();
        sb.AppendLine("namespace AutoMap");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class AutoMapExtensions");
        sb.AppendLine("    {");

        foreach (var m in valid)
        {
            sb.AppendLine($"        public static {m.DestFqn} {m.MethodName}(this {m.SourceFqn} src)");
            sb.AppendLine("        {");
            if (!m.IsSourceValueType)
                sb.AppendLine("            if (src is null) throw new ArgumentNullException(nameof(src));");

            var extras = resolvedExtras.TryGetValue(m, out var ex) ? ex : null;
            bool hasInitProps = m.Mappings.Length > 0 || (extras != null && extras.Count > 0);

            if (m.UseConstructor)
            {
                // Emit: new Dest(src.A, src.B, ...)
                var ctorArgs = string.Join(", ", m.CtorParams.Select(p =>
                    p.SourcePropertyName != null ? $"src.{p.SourcePropertyName}" : "default"));
                if (hasInitProps)
                {
                    sb.AppendLine($"            return new {m.DestFqn}({ctorArgs})");
                    sb.AppendLine("            {");
                    foreach (var p in m.Mappings)
                        sb.AppendLine($"                {p.DestPropertyName} = {p.CustomExpression ?? $"src.{p.SourcePropertyName}"},");
                    if (extras != null)
                        foreach (var (dp, expr) in extras)
                            sb.AppendLine($"                {dp} = {expr},");
                    sb.AppendLine("            };");
                }
                else
                {
                    sb.AppendLine($"            return new {m.DestFqn}({ctorArgs});");
                }
            }
            else
            {
                // Emit: new Dest { A = src.A, ... }
                sb.AppendLine($"            return new {m.DestFqn}");
                sb.AppendLine("            {");
                foreach (var p in m.Mappings)
                    sb.AppendLine($"                {p.DestPropertyName} = {p.CustomExpression ?? $"src.{p.SourcePropertyName}"},");
                if (extras != null)
                    foreach (var (dp, expr) in extras)
                        sb.AppendLine($"                {dp} = {expr},");
                sb.AppendLine("            };");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // IAutoMapper<TSource, TDest> implementations (static singleton per mapping)
        foreach (var m in valid)
        {
            var mapperName = $"{SimpleName(m.SourceFqn)}{m.MethodName}Mapper";
            sb.AppendLine($"        public sealed class {mapperName} : global::AutoMap.IAutoMapper<{m.SourceFqn}, {m.DestFqn}>");
            sb.AppendLine("        {");
            sb.AppendLine($"            public static readonly {mapperName} Instance = new {mapperName}();");
            sb.AppendLine($"            public {m.DestFqn} Map({m.SourceFqn} source) => source.{m.MethodName}();");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("AutoMapExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string SimpleName(string fqn)
    {
        var last = fqn.LastIndexOf('.');
        return last >= 0 ? fqn.Substring(last + 1) : fqn;
    }

    private static string? WrapWhen(string expr, string? condition, string? fallback) =>
        condition != null ? $"{condition} ? {expr} : {fallback ?? "default"}" : expr;

    // ── Enum mapping helper ───────────────────────────────────────────────────

    private static string BuildEnumSwitchExpression(
        string srcAccessExpr,
        INamedTypeSymbol srcEnum,
        INamedTypeSymbol destEnum,
        string destEnumFqn,
        ImmutableArray<DiagnosticInfo>.Builder diagnostics)
    {
        var srcEnumFqn = srcEnum.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Build dest value lookup (name → canonical name)
        var destMembers = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var m in destEnum.GetMembers())
            if (m is IFieldSymbol f && f.HasConstantValue)
                destMembers[f.Name] = f.Name;

        var sb = new StringBuilder();
        sb.Append(srcAccessExpr);
        sb.Append(" switch { ");

        foreach (var m in srcEnum.GetMembers())
        {
            if (m is not IFieldSymbol f || !f.HasConstantValue) continue;

            // Check [MapEnum("DestValueName")] on this source member
            string? destValueName = null;
            foreach (var a in f.GetAttributes())
            {
                if (a.AttributeClass?.ToDisplayString() == "AutoMap.MapEnumAttribute"
                    && a.ConstructorArguments.Length > 0)
                { destValueName = a.ConstructorArguments[0].Value as string; break; }
            }

            // Fall back to name-match
            if (destValueName == null)
                destMembers.TryGetValue(f.Name, out destValueName);

            if (destValueName == null)
            {
                diagnostics.Add(new DiagnosticInfo("AM006",
                    ImmutableArray.Create(f.Name, srcEnum.Name, destEnum.Name)));
                continue; // unmatched — covered by _ => default
            }

            sb.Append($"{srcEnumFqn}.{f.Name} => {destEnumFqn}.{destValueName}, ");
        }

        sb.Append("_ => default }");
        return sb.ToString();
    }

    // ── Flattening helper ─────────────────────────────────────────────────────

    /// <summary>
    /// Attempts to flatten a dest property name into a dotted source access path.
    /// E.g. "CustomerName" → "src.Customer?.Name" when source has Customer.Name.
    /// Returns null when no path can be found.
    /// </summary>
    private static string? TryFlattenPath(
        string name,
        Dictionary<string, IPropertySymbol> props,
        string currentExpr,
        bool accessViaNull,
        int depth)
    {
        if (depth >= 3) return null;

        for (int i = 1; i < name.Length; i++)
        {
            if (!char.IsUpper(name[i])) continue;

            var part = name.Substring(0, i);
            var rest = name.Substring(i);

            if (!props.TryGetValue(part, out var prop)) continue;
            if (prop.IsStatic || prop.IsIndexer) continue;
            if (prop.GetMethod?.DeclaredAccessibility != Accessibility.Public) continue;

            var accessOp = accessViaNull ? "?." : ".";
            var thisExpr = $"{currentExpr}{accessOp}{prop.Name}";

            if (prop.Type is not INamedTypeSymbol namedType) continue;

            var subProps = BuildReadablePropLookup(namedType);
            bool propIsRef = !prop.Type.IsValueType;

            if (subProps.TryGetValue(rest, out var subProp))
            {
                var op2 = propIsRef ? "?." : ".";
                return $"{thisExpr}{op2}{subProp.Name}";
            }

            var deeper = TryFlattenPath(rest, subProps, thisExpr, propIsRef, depth + 1);
            if (deeper != null) return deeper;
        }

        return null;
    }

    private static Dictionary<string, IPropertySymbol> BuildReadablePropLookup(INamedTypeSymbol type)
    {
        var dict = new Dictionary<string, IPropertySymbol>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in GetAllProperties(type))
        {
            if (p.IsStatic || p.IsIndexer) continue;
            if (p.GetMethod?.DeclaredAccessibility != Accessibility.Public) continue;
            if (!dict.ContainsKey(p.Name)) dict[p.Name] = p;
        }
        return dict;
    }
}

// ── Data models (equatable for incremental caching) ──────────────────────────

internal sealed class MappingInfo
{
    public string SourceFqn { get; }
    public string DestFqn { get; }
    public string MethodName { get; }
    public ImmutableArray<PropertyMapping> Mappings { get; }
    public ImmutableArray<UnresolvedProperty> UnresolvedProperties { get; }
    public ImmutableArray<DiagnosticInfo> Diagnostics { get; }
    public bool IsSourceValueType { get; }
    public ImmutableArray<CtorParamMapping> CtorParams { get; }

    public bool UseConstructor => CtorParams.Length > 0;

    public MappingInfo(string sourceFqn, string destFqn, string methodName,
        ImmutableArray<PropertyMapping> mappings,
        ImmutableArray<UnresolvedProperty> unresolvedProperties,
        ImmutableArray<DiagnosticInfo> diagnostics,
        bool isSourceValueType,
        ImmutableArray<CtorParamMapping> ctorParams = default)
    {
        SourceFqn = sourceFqn; DestFqn = destFqn; MethodName = methodName;
        Mappings = mappings; UnresolvedProperties = unresolvedProperties;
        Diagnostics = diagnostics; IsSourceValueType = isSourceValueType;
        CtorParams = ctorParams.IsDefault ? ImmutableArray<CtorParamMapping>.Empty : ctorParams;
    }
}

internal sealed class PropertyMapping
{
    public string DestPropertyName { get; }
    public string SourcePropertyName { get; }
    /// <summary>When non-null, emitted verbatim as the RHS instead of src.SourcePropertyName.</summary>
    public string? CustomExpression { get; }

    public PropertyMapping(string destPropertyName, string sourcePropertyName, string? customExpression = null)
    {
        DestPropertyName = destPropertyName;
        SourcePropertyName = sourcePropertyName;
        CustomExpression = customExpression;
    }
}

internal sealed class UnresolvedProperty
{
    public string DestPropertyName { get; }
    public string SourcePropertyName { get; }
    public string SourceTypeFqn { get; }
    public string DestTypeFqn { get; }
    public bool IsCollection { get; }
    public string? SourceElementFqn { get; }
    public string? DestElementFqn { get; }
    public string? DestCollectionKind { get; } // "List" | "Array"

    public UnresolvedProperty(string destPropertyName, string sourcePropertyName,
        string sourceTypeFqn, string destTypeFqn, bool isCollection,
        string? sourceElementFqn, string? destElementFqn, string? destCollectionKind)
    {
        DestPropertyName = destPropertyName; SourcePropertyName = sourcePropertyName;
        SourceTypeFqn = sourceTypeFqn; DestTypeFqn = destTypeFqn;
        IsCollection = isCollection; SourceElementFqn = sourceElementFqn;
        DestElementFqn = destElementFqn; DestCollectionKind = destCollectionKind;
    }
}

internal sealed class DiagnosticInfo
{
    public string Id { get; }
    public ImmutableArray<string> Args { get; }
    public DiagnosticInfo(string id, ImmutableArray<string> args) { Id = id; Args = args; }
}

internal sealed class CtorParamMapping
{
    public string ParamName { get; }       // C# param name (as declared)
    public string? SourcePropertyName { get; } // null → no match → emit default
    public CtorParamMapping(string paramName, string? sourcePropertyName)
    {
        ParamName = paramName; SourcePropertyName = sourcePropertyName;
    }
}
