using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AutoMap;

[Generator]
public sealed class AutoMapGenerator : IIncrementalGenerator
{
    // ── Attributes emitted into the user's compilation ────────────────────────

    private const string AttributeSource = @"// <auto-generated by AutoMap/>
#nullable enable
using System;

namespace AutoMap
{
    /// <summary>Generates a To{DestName}() extension method mapping this type to <paramref name=""destinationType""/>.</summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class MapAttribute : Attribute
    {
        public Type DestinationType { get; }
        /// <summary>Override the generated method name. Default: ""To{DestinationTypeName}"".</summary>
        public string? MethodName { get; set; }
        public MapAttribute(Type destinationType) { DestinationType = destinationType; }
    }

    /// <summary>Generates a To{ThisName}() extension method on <paramref name=""sourceType""/> that maps to this type.</summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class MapFromAttribute : Attribute
    {
        public Type SourceType { get; }
        /// <summary>Override the generated method name. Default: ""To{ThisTypeName}"".</summary>
        public string? MethodName { get; set; }
        public MapFromAttribute(Type sourceType) { SourceType = sourceType; }
    }

    /// <summary>Excludes this destination property from all generated mappings.</summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapIgnoreAttribute : Attribute { }

    /// <summary>Maps this destination property from a differently-named source property.</summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class MapPropertyAttribute : Attribute
    {
        public string SourceName { get; }
        public MapPropertyAttribute(string sourceName) { SourceName = sourceName; }
    }
}
";

    // ── Diagnostics ──────────────────────────────────────────────────────────

    private static readonly DiagnosticDescriptor AM001 = new DiagnosticDescriptor(
        "AM001",
        "No properties mapped",
        "Mapping from '{0}' to '{1}' produced no property matches. Ensure property names and types align, or add [MapIgnore] to suppress.",
        "AutoMap",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap#am001");

    private static readonly DiagnosticDescriptor AM002 = new DiagnosticDescriptor(
        "AM002",
        "MapProperty source name not found",
        "[MapProperty(\"{0}\")] on '{1}.{2}' references a property that does not exist on source type '{3}'",
        "AutoMap",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap#am002");

    private static readonly DiagnosticDescriptor AM003 = new DiagnosticDescriptor(
        "AM003",
        "Mapping target type could not be resolved",
        "The type passed to [{0}] on '{1}' could not be resolved. Ensure the type is accessible.",
        "AutoMap",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: "https://github.com/Swevo/AutoMap#am003");

    // ── Initialize ────────────────────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("AutoMapAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // [Map] — attribute sits on the source type
        var mapPipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoMap.MapAttribute",
                predicate: static (n, _) => IsTypeSyntax(n),
                transform: static (ctx, ct) => TransformAttributes(ctx, ct, isMapFrom: false))
            .SelectMany(static (arr, _) => arr);

        // [MapFrom] — attribute sits on the destination type
        var mapFromPipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoMap.MapFromAttribute",
                predicate: static (n, _) => IsTypeSyntax(n),
                transform: static (ctx, ct) => TransformAttributes(ctx, ct, isMapFrom: true))
            .SelectMany(static (arr, _) => arr);

        var allMappings = mapPipeline.Collect().Combine(mapFromPipeline.Collect());

        context.RegisterSourceOutput(allMappings, static (spc, pair) =>
            GenerateSource(spc, pair.Left.AddRange(pair.Right)));
    }

    private static bool IsTypeSyntax(SyntaxNode n) =>
        n is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax;

    // ── Transform: one call per decorated type, returns one MappingInfo per attribute ─

    private static ImmutableArray<MappingInfo> TransformAttributes(
        GeneratorAttributeSyntaxContext ctx,
        System.Threading.CancellationToken ct,
        bool isMapFrom)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol decoratedSymbol)
            return ImmutableArray<MappingInfo>.Empty;

        var builder = ImmutableArray.CreateBuilder<MappingInfo>(ctx.Attributes.Length);

        foreach (var attr in ctx.Attributes)
        {
            ct.ThrowIfCancellationRequested();

            if (attr.ConstructorArguments.Length == 0) continue;
            if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol otherSymbol)
            {
                // AM003 — type could not be resolved
                builder.Add(new MappingInfo(
                    string.Empty, string.Empty, string.Empty,
                    ImmutableArray<PropertyMapping>.Empty,
                    ImmutableArray.Create(new DiagnosticInfo("AM003",
                        ImmutableArray.Create(isMapFrom ? "MapFromAttribute" : "MapAttribute", decoratedSymbol.Name))),
                    false));
                continue;
            }

            var sourceSymbol = isMapFrom ? otherSymbol : decoratedSymbol;
            var destSymbol   = isMapFrom ? decoratedSymbol : otherSymbol;

            string? methodName = null;
            foreach (var na in attr.NamedArguments)
                if (na.Key == "MethodName") { methodName = na.Value.Value as string; break; }

            builder.Add(BuildMappingInfo(sourceSymbol, destSymbol, methodName, ctx.SemanticModel.Compilation));
        }

        return builder.ToImmutable();
    }

    // ── Build one MappingInfo from resolved symbols ───────────────────────────

    private static MappingInfo BuildMappingInfo(
        INamedTypeSymbol sourceSymbol,
        INamedTypeSymbol destSymbol,
        string? methodName,
        Compilation compilation)
    {
        var sourceFqn = sourceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var destFqn   = destSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var effectiveMethod = methodName ?? "To" + destSymbol.Name;

        // Build a lookup of all readable source properties (name → symbol)
        var sourceProps = new Dictionary<string, IPropertySymbol>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in GetAllProperties(sourceSymbol))
        {
            if (p.IsStatic || p.IsIndexer) continue;
            if (p.GetMethod == null || p.GetMethod.DeclaredAccessibility != Accessibility.Public) continue;
            if (!sourceProps.ContainsKey(p.Name))
                sourceProps[p.Name] = p;
        }

        var mappings    = ImmutableArray.CreateBuilder<PropertyMapping>();
        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticInfo>();

        foreach (var destProp in GetAllProperties(destSymbol))
        {
            if (destProp.IsStatic || destProp.IsIndexer) continue;

            // Must have a publicly accessible setter (regular or init)
            var setter = destProp.SetMethod;
            if (setter == null || setter.DeclaredAccessibility != Accessibility.Public) continue;

            // [MapIgnore]
            if (HasAttribute(destProp, "AutoMap.MapIgnoreAttribute")) continue;

            // [MapProperty("SourceName")]
            string? srcOverrideName = null;
            foreach (var a in destProp.GetAttributes())
            {
                if (a.AttributeClass?.ToDisplayString() == "AutoMap.MapPropertyAttribute"
                    && a.ConstructorArguments.Length > 0)
                {
                    srcOverrideName = a.ConstructorArguments[0].Value as string;
                    break;
                }
            }

            string lookupName = srcOverrideName ?? destProp.Name;

            if (!sourceProps.TryGetValue(lookupName, out var srcProp))
            {
                if (srcOverrideName != null)
                {
                    // AM002 — explicit source name missing
                    diagnostics.Add(new DiagnosticInfo("AM002",
                        ImmutableArray.Create(srcOverrideName, destSymbol.Name, destProp.Name, sourceSymbol.Name)));
                }
                continue;
            }

            // Type must be identity or have an implicit conversion
            var csharp = compilation as Microsoft.CodeAnalysis.CSharp.CSharpCompilation;
            if (csharp != null)
            {
                var conv = csharp.ClassifyConversion(srcProp.Type, destProp.Type);
                if (!conv.IsIdentity && !conv.IsImplicit) continue;
            }
            else
            {
                // Fallback: FQN match (strips nullability annotation)
                var srcTypeFqn  = srcProp.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).TrimEnd('?');
                var destTypeFqn = destProp.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).TrimEnd('?');
                if (srcTypeFqn != destTypeFqn) continue;
            }

            mappings.Add(new PropertyMapping(destProp.Name, lookupName));
        }

        if (mappings.Count == 0 && diagnostics.Count == 0)
        {
            diagnostics.Add(new DiagnosticInfo("AM001",
                ImmutableArray.Create(sourceSymbol.Name, destSymbol.Name)));
        }

        return new MappingInfo(
            sourceFqn, destFqn, effectiveMethod,
            mappings.ToImmutable(),
            diagnostics.ToImmutable(),
            sourceSymbol.IsValueType);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static IEnumerable<IPropertySymbol> GetAllProperties(INamedTypeSymbol type)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var current = (INamedTypeSymbol?)type;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is IPropertySymbol prop && seen.Add(prop.Name))
                    yield return prop;
            }
            current = current.BaseType;
        }
    }

    private static bool HasAttribute(ISymbol symbol, string fullyQualifiedName)
    {
        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.ToDisplayString() == fullyQualifiedName)
                return true;
        return false;
    }

    // ── Code generation ───────────────────────────────────────────────────────

    private static void GenerateSource(
        SourceProductionContext spc,
        ImmutableArray<MappingInfo> mappings)
    {
        // Report diagnostics
        foreach (var m in mappings)
        {
            foreach (var d in m.Diagnostics)
            {
                var descriptor = d.Id switch
                {
                    "AM001" => AM001,
                    "AM002" => AM002,
                    _       => AM003,
                };
                spc.ReportDiagnostic(
                    Diagnostic.Create(descriptor, null, d.Args.ToArray<object>()));
            }
        }

        var valid = mappings.Where(static m => m.Mappings.Length > 0).ToList();
        if (valid.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoMap/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoMap");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class AutoMapExtensions");
        sb.AppendLine("    {");

        foreach (var m in valid)
        {
            sb.AppendLine($"        public static {m.DestFqn} {m.MethodName}(this {m.SourceFqn} src)");
            sb.AppendLine("        {");
            if (!m.IsSourceValueType)
                sb.AppendLine("            if (src is null) throw new ArgumentNullException(nameof(src));");
            sb.AppendLine($"            return new {m.DestFqn}");
            sb.AppendLine("            {");
            foreach (var p in m.Mappings)
                sb.AppendLine($"                {p.DestPropertyName} = src.{p.SourcePropertyName},");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("AutoMapExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

// ── Data models (equatable for incremental caching) ──────────────────────────

internal sealed class MappingInfo
{
    public string SourceFqn { get; }
    public string DestFqn { get; }
    public string MethodName { get; }
    public ImmutableArray<PropertyMapping> Mappings { get; }
    public ImmutableArray<DiagnosticInfo> Diagnostics { get; }
    public bool IsSourceValueType { get; }

    public MappingInfo(string sourceFqn, string destFqn, string methodName,
        ImmutableArray<PropertyMapping> mappings, ImmutableArray<DiagnosticInfo> diagnostics,
        bool isSourceValueType)
    {
        SourceFqn = sourceFqn; DestFqn = destFqn; MethodName = methodName;
        Mappings = mappings; Diagnostics = diagnostics; IsSourceValueType = isSourceValueType;
    }
}

internal sealed class PropertyMapping
{
    public string DestPropertyName { get; }
    public string SourcePropertyName { get; }
    public PropertyMapping(string destPropertyName, string sourcePropertyName)
    {
        DestPropertyName = destPropertyName; SourcePropertyName = sourcePropertyName;
    }
}

internal sealed class DiagnosticInfo
{
    public string Id { get; }
    public ImmutableArray<string> Args { get; }
    public DiagnosticInfo(string id, ImmutableArray<string> args) { Id = id; Args = args; }
}
